server:
  port: 8089
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: "classpath:/db/migration"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect